export interface IExercise<T = string> {
	id: string
	name: string
	bodyParts: bodyPart[]
	description?: string
	image: T
	videoUrl?: string
	isPublic: boolean
	editable: boolean
}

export enum bodyPart {
	ABDOMINALS = 'ABDOMINALS',
	BACK = 'BACK',
	BICEPS = 'BICEPS',
	CALVES = 'CALVES',
	CHEST = 'CHEST',
	CORE = 'CORE',
	FOREARM = 'FOREARM',
	GLUTES = 'GLUTES',
	HAMSTRING = 'HAMSTRING',
	HAMSTRINGS = 'HAMSTRINGS',
	HIP_ABDUCTORS = 'HIP_ABDUCTORS',
	LATERAL_DELTOID = 'LATERAL_DELTOID',
	LATS = 'LATS',
	LOWER_ABDOMINALS = 'LOWER_ABDOMINALS',
	LOWER_BACK = 'LOWER_BACK',
	MIDDLE_BACK = 'MIDDLE_BACK',
	NECK = 'NECK',
	NECK_EXTENSORS = 'NECK_EXTENSORS',
	NECK_FLEXORS = 'NECK_FLEXORS',
	NECK_SIDE_FLEXORS = 'NECK_SIDE_FLEXORS',
	OBLIQUES = 'OBLIQUES',
	POSTERIOR_DELTOID = 'POSTERIOR_DELTOID',
	QUADRICEPS = 'QUADRICEPS',
	REAR_DELTOID = 'REAR_DELTOID',
	SHOULDER = 'SHOULDER',
	SHOULDERS = 'SHOULDERS',
	TRAPEZIUS = 'TRAPEZIUS',
	TRICEPS = 'TRICEPS',
	UPPER_BACK = 'UPPER_BACK'
}
